version: '3'
services:
  wps:
    build: .
    image: climateintelligence/albatross
    ports:
      - "5000:5000"


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
