name: nipa_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.11
  - pytest=8.3.5
  - pydap
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - -r file:requirements.txt
