name: nipaenv
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - _anaconda_depends=2024.02
  - abseil-cpp
  - aiobotocore
  - aiohttp
  - aioitertools
  - aiosignal
  - alabaster
  - anaconda-anon-usage
  - anaconda-catalogs
  - anaconda-client
  - anaconda-cloud-auth
  - anaconda-navigator
  - anaconda-project
  - anyio
  - aom
  - appdirs
  - applaunchservices
  - appnope
  - appscript
  - archspec
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - arrow-cpp
  - astroid
  - asttokens
  - async-lru
  - atomicwrites
  - autoflake
  - automat
  - autopep8
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - babel
  - backports
  - backports.functools_lru_cache
  - backports.tempfile
  - backports.weakref
  - basemap
  - basemap-data
  - basemap-data-hires
  - bcrypt
  - beautifulsoup4
  - binaryornot
  - black
  - blas
  - bleach
  - blosc
  - bokeh
  - boltons
  - boost-cpp
  - botocore
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cctools
  - cctools_osx-arm64
  - certifi
  - cffi
  - cfitsio
  - charls
  - cloudpickle
  - colorama
  - colorcet
  - comm
  - conda
  - conda-build
  - conda-content-trust
  - conda-index
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-repo-cli
  - conda-token
  - conda-verify
  - constantly
  - cookiecutter
  - cryptography
  - cssselect
  - curl
  - cyrus-sasl
  - cytoolz
  - dask
  - dask-core
  - datashader
  - dav1d
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - dill
  - distributed
  - distro
  - docopt-ng
  - docstring-to-markdown
  - docutils
  - entrypoints
  - et_xmlfile
  - executing
  - filelock
  - flake8
  - flask
  - fmt
  - freetype
  - frozendict
  - frozenlist
  - fsspec
  - future
  - gensim
  - geos
  - gettext
  - gflags
  - giflib
  - glib
  - glib-tools
  - glog
  - gmp
  - gmpy2
  - greenlet
  - grpc-cpp
  - gst-plugins-base
  - gstreamer
  - gtest
  - h5py
  - hdf5
  - heapdict
  - holoviews
  - hvplot
  - hyperlink
  - icu
  - imagecodecs
  - imageio
  - imagesize
  - imbalanced-learn
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - incremental
  - inflection
  - intake
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itemadapter
  - itemloaders
  - itsdangerous
  - jaraco.classes
  - jedi
  - jellyfish
  - jmespath
  - joblib
  - jpeg
  - jq
  - json5
  - jsonpatch
  - jsonpointer
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab-variableinspector
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - keyring
  - krb5
  - lazy-object-proxy
  - lazy_loader
  - lcms2
  - ld64
  - ld64_osx-arm64
  - ldid
  - legacy-cgi
  - lerc
  - libaec
  - libarchive
  - libavif
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - liblief
  - libllvm14
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsolv
  - libspatialindex
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - libzopfli
  - linkify-it-py
  - llvm-openmp
  - locket
  - lxml
  - lz4
  - lz4-c
  - lzo
  - markdown
  - markdown-it-py
  - matplotlib-inline
  - mccabe
  - mdit-py-plugins
  - mdurl
  - menuinst
  - mistune
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multidict
  - multipledispatch
  - munkres
  - mypy
  - mypy_extensions
  - mysql
  - navigator-updater
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nltk
  - notebook
  - notebook-shim
  - numexpr
  - numpydoc
  - oniguruma
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - overrides
  - pandocfilters
  - panel
  - param
  - parsel
  - parso
  - partd
  - patch
  - pathlib
  - pathspec
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pip
  - pkce
  - pkginfo
  - platformdirs
  - plotly
  - ply
  - proj
  - prometheus_client
  - prompt-toolkit
  - protego
  - psutil
  - ptyprocess
  - pure_eval
  - py-cpuinfo
  - py-lief
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycodestyle
  - pycosat
  - pycparser
  - pyct
  - pycurl
  - pydantic
  - pydap
  - pydispatcher
  - pydocstyle
  - pyflakes
  - pygments
  - pyjwt
  - pylint
  - pylint-venv
  - pyls-spyder
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyobjc-framework-coreservices
  - pyobjc-framework-fsevents
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyqtwebengine
  - pyshp
  - pysocks
  - pytables
  - python
  - python-dotenv
  - python-fastjsonschema
  - python-json-logger
  - python-libarchive-c
  - python-lmdb
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python-snappy
  - python-tzdata
  - python.app
  - python_abi
  - pytoolconfig
  - pyviz_comms
  - pyzmq
  - qdarkstyle
  - qhull
  - qstylizer
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtpy
  - queuelib
  - re2
  - readline
  - regex
  - reproc
  - reproc-cpp
  - requests
  - requests-file
  - requests-toolbelt
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rope
  - rtree
  - ruamel.yaml
  - ruamel_yaml
  - s3fs
  - scikit-image
  - scikit-learn
  - scrapy
  - seaborn
  - semver
  - send2trash
  - service_identity
  - setuptools
  - sip
  - six
  - smart_open
  - snappy
  - sniffio
  - snowballstemmer
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - stack_data
  - statsmodels
  - sympy
  - tabulate
  - tapi
  - tbb
  - tblib
  - terminado
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tinycss2
  - tk
  - tldextract
  - toml
  - tomlkit
  - toolz
  - tornado
  - tqdm
  - traitlets
  - truststore
  - twisted
  - tzdata
  - tzlocal
  - uc-micro-py
  - ujson
  - unidecode
  - unixodbc
  - utf8proc
  - validators
  - w3lib
  - watchdog
  - wcwidth
  - webencodings
  - webob
  - werkzeug
  - whatthepatch
  - wheel
  - widgetsnbextension
  - wurlitzer
  - xarray
  - xlwings
  - xyzservices
  - xz
  - yaml
  - yaml-cpp
  - yapf
  - yarl
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zope
  - zope.interface
  - zstandard
  - zstd
  - pip:
      - absl-py==2.1.0
      - altair==5.5.0
      - asciitree==0.3.3
      - astropy==7.0.1
      - astropy-iers-data==0.2025.3.17.0.34.53
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - cads-api-client==1.0.3
      - cdsapi==0.7.0
      - chardet==3.0.4
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - clyent==1.2.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - deepdiff==7.0.1
      - deprecated==1.2.18
      - docopt==0.6.2
      - enum34==1.1.10
      - fasteners==0.19
      - fiona==1.10.1
      - fonttools==4.56.0
      - fst-pso==1.8.1
      - fuzzytm==2.0.9
      - geotiff==0.2.10
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gym==0.26.2
      - gym-notices==0.0.8
      - humanize==4.12.1
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.6
      - jsonpickle==3.0.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lbforaging==1.1.1
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.8.4
      - miniful==0.0.6
      - mock==5.1.0
      - mpyq==0.2.5
      - multiurl==0.3.1
      - munch==4.0.0
      - narwhals==1.31.0
      - numba==0.61.0
      - numcodecs==0.15.1
      - numpy==1.24.4
      - ordered-set==4.1.0
      - owslib==0.32.1
      - packaging==23.2
      - pandas==1.5.3
      - pbr==4.3.0
      - pillow==11.1.0
      - pluggy==0.7.1
      - portpicker==1.2.0
      - probscale==0.2.5
      - protobuf==3.20.3
      - py==1.11.0
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pyerfa==2.0.1.5
      - pyfume==0.3.4
      - pygame==2.5.2
      - pyglet==2.0.15
      - pyproj==3.7.1
      - pysc2==3.0.0
      - pytest==8.3.5
      - python-dateutil==2.8.2
      - pytz==2025.1
      - pywavelets==1.8.0
      - pywps>=4.4
      - pyyaml==6.0.1
      - referencing==0.36.2
      - requests-mock==1.12.1
      - rpds-py==0.23.1
      - rpy2==3.5.16
      - rware==1.0.3
      - s2clientprotocol==4.10.1.75800.0
      - s2protocol==5.0.12.91115.0
      - sacred==0.8.5
      - scipy==1.10.1
      - simpful==2.12.0
      - sk-video==1.1.10
      - smac==1.0.0
      - smmap==5.0.2
      - snakeviz==2.2.0
      - stats==0.1.2a0
      - streamlit==1.43.2
      - tenacity==9.0.0
      - tensorboard-logger==0.1.0
      - torch==2.3.0
      - torchvision==0.18.0
      - typing-extensions==4.12.2
      - urllib3==2.0.7
      - websocket-client==0.53.0
      - whichcraft==0.5.2
      - wrapt==1.17.2
      - zarr==2.12.0
